config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  get '/chat', to: 'home#index'
  get '/get_current_user', to: 'home#get_current_user'
  get '/messages', to: 'home#messages'
  post '/messages', to: 'home#create_message'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def get_current_user
    respond_to do |format|
      format.json do
        render json: current_user.as_json
      end
    end
  end

  def messages
    respond_to do |format|
      format.json do
        render json: Message.all.as_json(include: :user)
      end
    end
  end

  def create_message
    respond_to do |format|
      format.json do
        message = Message.create(user: current_user, message: params[:message])
        return unless message

        ActionCable.server.broadcast("chatroom", message: message.as_json, user: message.user.as_json)
      end
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, :only => [:create]

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<%= javascript_pack_tag 'app' %>

<div id="app">
  <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
    <div class="container">
        <a class="navbar-brand" href="<%= root_url %>">
          Realtime Chat App
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">

            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                <% if current_user.blank? %>
                    <li class="nav-item">
                        <a class="nav-link" href="<%= new_session_path(resource_name) %>">Login</a>
                    </li>
                    <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
                        <li class="nav-item">
                            <a class="nav-link" href="<%= new_registration_path(resource_name) %>">Register</a>
                        </li>
                    <% end %>
                <% else %>
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            <%= current_user.name %> <span class="caret"></span>
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="<%= destroy_user_session_path %>">
                                Logout
                            </a>
                        </div>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chat App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <%= yield :additional_script %>
    <%= yield :additional_stylesheet %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>